// Package render writes .bluepave/resolved.yaml: the enabled modules in install order, their
// settings and the active profile, resolved from bluepave.yaml (ADR-0002). The GitOps root chart
// reads it as a values file, so the cluster gets the same module set the CLI resolved, without
// Helm having to understand profiles or requirements.
package render

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"go.yaml.in/yaml/v3"

	"github.com/kushan94/bluepave/internal/config"
	"github.com/kushan94/bluepave/internal/modules"
)

// Path is where the resolved file lives, relative to the repository root.
const Path = ".bluepave/resolved.yaml"

const header = `# Generated by ` + "`bluepave render`" + ` from bluepave.yaml, the profile and the module manifests.
# Do not edit: CI fails when it's out of date. The GitOps root chart (platform/chart) reads it.
`

// Resolved is the content of .bluepave/resolved.yaml (under the top-level key "resolved", so it
// can't collide with bluepave.yaml's keys when both are Helm values files).
type Resolved struct {
	Profile     string         `yaml:"profile"`
	ProfileSpec map[string]any `yaml:"profileSpec"`
	Modules     []Module       `yaml:"modules"`
}

// Module is one enabled module.
type Module struct {
	Name      string             `yaml:"name"`
	Version   string             `yaml:"version"`
	Gitops    string             `yaml:"gitops,omitempty"` // chart path, relative to the repository root
	Sources   []modules.Source   `yaml:"sources,omitempty"`
	Hostnames []modules.Hostname `yaml:"hostnames,omitempty"`
	Settings  map[string]any     `yaml:"settings,omitempty"`
}

// Build resolves the platform's modules. ordered must come from modules.Resolve.
func Build(root string, p *config.Platform, ordered []*modules.Module) (*Resolved, error) {
	profileSpec, err := rawSpec(filepath.Join(root, "profiles", p.Spec.Profile+".yaml"))
	if err != nil {
		return nil, err
	}
	r := &Resolved{Profile: p.Spec.Profile, ProfileSpec: profileSpec, Modules: []Module{}}
	for _, m := range ordered {
		out := Module{
			Name:      m.Metadata.Name,
			Version:   m.Spec.Version,
			Sources:   m.Spec.Sources,
			Hostnames: m.Spec.Hostnames,
			Settings:  p.Spec.Modules[m.Metadata.Name].Settings,
		}
		if g, ok := m.Spec.Layers["gitops"]; ok {
			rel, err := filepath.Rel(root, filepath.Join(m.Dir, g))
			if err != nil {
				return nil, err
			}
			out.Gitops = filepath.ToSlash(rel)
		}
		r.Modules = append(r.Modules, out)
	}
	return r, nil
}

// Marshal returns the file's content.
func (r *Resolved) Marshal() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(map[string]any{"resolved": r}); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Write writes the file to path. With check, it writes nothing and returns an error if the file
// on disk differs.
func (r *Resolved) Write(path string, check bool) error {
	want, err := r.Marshal()
	if err != nil {
		return err
	}
	if check {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			return fmt.Errorf("%s is out of date: run `bluepave render` and commit it", path)
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, want, 0o644)
}

func rawSpec(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc struct {
		Spec map[string]any `yaml:"spec"`
	}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	return doc.Spec, nil
}
