package render

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"go.yaml.in/yaml/v3"

	"github.com/kushan94/bluepave/internal/config"
)

// SettingsFile is the platform-settings catalog entity, written next to resolved.yaml. The root
// catalog-info.yaml lists it, so the portal reads it from the repository: from GitHub when hosted,
// from the checkout when run locally.
const SettingsFile = "platform-settings.yaml"

// Revision is the branch the platform deploys from (Argo CD's root Application) and that the
// portal's templates open pull requests against.
const Revision = "main"

const settingsHeader = `# Generated by ` + "`bluepave render`" + ` from bluepave.yaml. Do not edit: CI fails when it's out of date.
# What the portal's templates need to know about the platform (modules/portal/templates).
`

// Settings is the platform-settings entity: a Backstage Resource whose annotations carry the
// platform's GitHub owner and repository, and the environment and domain new services start in
// (the first environment).
func Settings(p *config.Platform) ([]byte, error) {
	env := p.Spec.Environments[0]
	entity := map[string]any{
		"apiVersion": "backstage.io/v1alpha1",
		"kind":       "Resource",
		"metadata": map[string]any{
			"name":        "platform-settings",
			"title":       "Platform settings",
			"description": "What the portal's templates need to know about this platform (generated by bluepave render)",
			"annotations": map[string]string{
				"github.com/project-slug":    p.Spec.GitHub.Owner + "/" + p.Spec.GitHub.PlatformRepo,
				"bluepave.dev/github-owner":  p.Spec.GitHub.Owner,
				"bluepave.dev/platform-repo": p.Spec.GitHub.PlatformRepo,
				"bluepave.dev/revision":      Revision,
				"bluepave.dev/environment":   env,
				"bluepave.dev/domain":        env + "." + p.Spec.DNS.Domain,
			},
		},
		"spec": map[string]any{"type": "platform-settings", "owner": "platform-team", "system": "platform"},
	}
	var buf bytes.Buffer
	buf.WriteString(settingsHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(entity); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// WriteSettings writes the entity to path, or with check, fails if the file on disk differs.
func WriteSettings(p *config.Platform, path string, check bool) error {
	want, err := Settings(p)
	if err != nil {
		return err
	}
	if check {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			return fmt.Errorf("%s is out of date: run `bluepave render` and commit it", path)
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, want, 0o644)
}
